#!/bin/bash
#echo $(ip addr show enp4s0f0 | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
#echo $IP
set -o nounset -o errexit -o pipefail
export PATH=/sbin:/usr/sbin:/bin:/usr/bin:$PATH
#MASTER_IP=$(dig +short master.mesos || true)
MASTER_IP=${MASTER_IP:-192.168.131.8}
INTERFACE_IP=$(ip r g ${MASTER_IP} | awk -F ' ' '{print $5}')
echo $INTERFACE_IP
